### ISSUE TITLE
Test with Elasticsearch

### ISSUE THREAD

**Issue by demitree** [matteodem/easy-search-leaderboard#13]
I tried to use elastic-search as search engine in this project, I activate the  'es' part and comment the 'mongodb' part and it works, though I'm not sure about the result. Following the part that concerns:

EasySearch.createSearchIndex('players', {
  'collection': Players, // instanceof Meteor.Collection
  'field': ['Name'], // array of fields to be searchable
  'limit': 10,
  'use' : 'elastic-search',
  'convertNumbers': true,
  'props': {
    'filteredCategory': 'All',
    'sortBy': 'score'
  },
  'sort': function() {
    return ['_score'];
  }
});

We can tell that it uses a Mongodb collection called Players, how can it do the elastic search with a mongodb collection? Otherwise, I don't find where we configure the elasticsearch index and type.

**Comment by demitree** [comment]
I've created a temp collection, fill it with part of 'players' data and use this collection to do the search, the collection is well charged and it copies all documents to elasticsearch(checked), but for searching, it doesn't work. Which is bizare to me since the only difference is the collection

**Comment by matteodem** [comment]
What is the exact question here?

**Comment by demitree** [comment]
Sorry, I've already figured out the first one, so  the second one

**Comment by matteodem** [comment]
What do you mean, please rephrase your question with reproduction steps if needed.

**Comment by demitree** [comment]
I clone this project. At first i want to use my own mongodb collection but there's a lot problems so I've just half-copied your collection, the new collection contains part of your origin collection data. 

Your origin collection :  
"players" : p1, p2, p3....

New created collection : 
"test" : p1, p3 ...

then I use the collection "test" to run with elasticsearch, it failed.

BTW, I simplified the whole project to display only a searchbar and resultlist.  So I've only changed the following line:

test = new Meteor.Collection('player'); 

to 

test = new Meteor.Collection('test');

and following the definition of searchIndex : 

EasySearch.createSearchIndex('test', {
  'collection': test,
  'field': ['name'],
  'use' : 'elastic-search',
  'query': function(searchString) {
    var query = {
      "fuzzy_like_this":{
        "fields" : ["name"],
        "like_text" : searchString
      }
    };
    console.log(query);
    return query;
  }
});

**Comment by matteodem** [comment]
did you start Elastic Search as a seperate process? see http://matteodem.github.io/meteor-easy-search/docs/elastic-search/

**Comment by demitree** [comment]
Elastic search is launched automatically and working well. And I've tried elastic search with your collection, that works.

**Comment by matteodem** [comment]
Then all is fine I assume

**Comment by demitree** [comment]
NO, the last post just respond your last question...Which means that es works for your collection, but for another collection it doesn't work I really don't understand how could that be.

**Comment by matteodem** [comment]
G

**Comment by matteodem** [comment]
Give me an github repository with reproduction steps. (Otherwise I can't help you)

**Comment by matteodem** [comment]
What is the state of this?
